Import Numpy 

In [3]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [ ]:
a= [1,2,3,4.5,5] #one dimensioanl
a

[1, 2, 3, 4.5, 5]

In [9]:
np.array(a)

array([1. , 2. , 3. , 4.5, 5. ])

In [ ]:
l = [[1,2,3],[4,5,6],[7,8,9]] #two dimensional
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [ ]:
np.array(l) #two dimensional matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation Function

In [ ]:
arr = np.arange(1,11,2) # from 1 to 11 with a skip of 2 steps
arr

array([1, 3, 5, 7, 9])

Genenerate zeros

In [ ]:
arr = np.zeros((4,6)) # 4rows and 6 columns - all zeros
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Generate Ones

In [20]:
arr = np.ones((7,3))

arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Genenerate linear space between two numbers

In [22]:
arr = np.linspace(1,7,4)
arr

array([1., 3., 5., 7.])

Random Generation Functions

In [25]:
np.random.rand(10)

array([0.0288171 , 0.51374818, 0.21579973, 0.06499163, 0.23109047,
       0.24338799, 0.99058924, 0.44567877, 0.25374677, 0.83190981])

In [26]:
np.random.randn(10)

array([ 3.02756916,  0.14455553, -0.54283511, -0.75299518,  0.96488421,
       -0.73167365,  0.65916339, -1.25039633,  0.75856409,  0.19044635])

In [ ]:
np.random.randint(5,20,10) # 10 random numbers between 5 and 20

array([ 7, 19, 18,  5,  7,  6, 12, 13, 18, 18], dtype=int32)

Array Attributes

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
arr.shape

(3, 3)

In [37]:
arr.size

9

In [38]:
arr.dtype

dtype('int64')

Array Methods

In [39]:
arr.min()

np.int64(1)

In [40]:
arr.max()

np.int64(9)

In [41]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,axis=1)#row wise summation
np.sum(arr,axis=0) #column wise summation


array([12, 15, 18])

In [ ]:
arr.mean() #middle value

np.float64(5.0)

In [ ]:
arr.std() #standard deviation 

np.float64(2.581988897471611)

In [ ]:
arr.argmax() #position of the max value

np.int64(8)

In [ ]:
arr.argmin() #position of the min value

np.int64(0)

Reshaping and resizing

In [10]:
arr= np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [13]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])