Numpy Indexing and Slicing of Vectors

In [2]:
import numpy as np

In [3]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[5] #indexing

np.int64(16)

In [ ]:
arr[1::6] #slicing

array([12, 18])

Numpy indexing and slicing of Matrix

In [8]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [9]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[4,4]

np.int64(25)

In [14]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [15]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[:,2] #slicing out any column

array([ 3,  8, 13, 18, 23, 28])

Bollean Indexing

In [25]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [26]:
bool_index = arr%2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [27]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])